
name: "Build and Test"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: "Running Flutter Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_apk:
    name: "Building APK"
    needs: [flutter_test]
    runs-on: ubuntu-latest

    steps:
      #1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk